### ISSUE TITLE
Update for changes in retext

### ISSUE THREAD

**Issue by wooorm** [reshape/retext#14]
Hi! 👋

retext just changed: you can read more about the changed [here][1].

That means that this plugin doesn’t work with the latest retext. If you get around to updating, use the previously mentioned changelog for help, but feel free to respond below or ask questions on [Gitter][2]!

[1]: https://github.com/wooorm/retext/releases/tag/5.0.0
[2]: https://gitter.im/wooorm/retext

**Comment by jescalan** [comment]
Ok, all up to date now 😁
