### ISSUE TITLE
retext-skip for script tag by default

### ISSUE THREAD

**Issue by kbytin** [reshape/retext#4]
It took some time to figure out why script is not working.  

Retext transformed all quotes

**Comment by jescalan** [comment]
Ah yeah sorry, that can be a nasty issue. You can skip any given tag with [the `reshape-skip` option](https://github.com/reshape/retext#skipping-tags). I think perhaps it should automatically skip certain tags like `script` and `style` though. I can patch this today. Any other ideas for tags to auto-skip?

**Comment by jescalan** [comment]
So adding `pre` and `code` to this list, along with `script` and `style`.

Will implement these four today, any other ideas welcome!

**Comment by jescalan** [comment]
Fixed by `reshape-retext@0.3.0` 🎉

**Comment by kbytin** [comment]
Skipped that by retext-skip.  No other ideas yet, but I'll work on them
